'==============================================================================
'   WARNING!!  This file is overwritten by the UIStyler each time the Styler
'   file is saved.
'
'       Filename:  BEMHouse.vb
'
'        This file was generated by the NX User Interface Styler
'        Created by: csen
'        Version: NX 11
'              Date: 01-16-2022
'              Time: 13:04
'
'   This template file is overwritten each time the UIStyler dialog is
'   saved.  Any modifications to this file will be lost.
'==============================================================================


'==============================================================================
'  Purpose:  This TEMPLATE file contains VB.NET source to guide you in the
'  construction of your NX Open application dialog. The generation of your
'  dialog file (.dlg extension) is the first step towards dialog construction
'  within NX.  You must now create a NX Open application that
'  utilizes this file (.dlg).


'  The information in this file provides you with the following:
'
'  1.  Help on how to load and display your UIStyler dialog in NX
'      using APIs provided in NXOpen.UIStyler namespace
'  2.  The empty callback methods (stubs) associated with your dialog items
'      have also been placed in this file. These empty methods have been
'      created simply to start you along with your coding requirements.
'      The method name, argument list and possible return values have already
'      been provided for you.
'==============================================================================


'------------------------------------------------------------------------------
' These imports are needed for the following template code
'------------------------------------------------------------------------------
Option Strict Off
Imports System
Imports NXOpen
Imports NXOpen.UIStyler


'------------------------------------------------------------------------------
' Represents UI Styler application class
'------------------------------------------------------------------------------
Public Class BEMHouse
    ' class members
    Private Shared theSession As Session
    Private Shared theUI As UI
    Public Shared theBEMHouse As BEMHouse
    Private theDialog As Dialog
    Private changeDialog As NXOpen.UIStyler.DialogItem
    Private changeCgBeg1 As NXOpen.UIStyler.CollapsibleGroup
    Private changeCity As NXOpen.UIStyler.OptionMenu
    Private changeXAngle As NXOpen.UIStyler.RealItem
    Private changeLabel3 As NXOpen.UIStyler.LabelItem
    Private changeSolstice As NXOpen.UIStyler.OptionMenu
    Private changeCgBeg0 As NXOpen.UIStyler.CollapsibleGroup
    Private changeHeight As NXOpen.UIStyler.RealItem
    Private changeRoofHeight As NXOpen.UIStyler.RealItem
    Private changeWindowAreaDefault As NXOpen.UIStyler.RealItem
    Private changeWindowAspectDefault As NXOpen.UIStyler.RealItem
    Private changeTI As NXOpen.UIStyler.RealItem
    Private changeSep12 As NXOpen.UIStyler.Separator
    Private changeInputChromosomeString As NXOpen.UIStyler.StringItem
    Private changeBuildHouseFromChromosome As NXOpen.UIStyler.PushButton
    Private changeCgBeg8 As NXOpen.UIStyler.CollapsibleGroup
    Private changeLabel9 As NXOpen.UIStyler.LabelItem
    Private changeLabel10 As NXOpen.UIStyler.LabelItem
    Private changeLabel11 As NXOpen.UIStyler.LabelItem
    Private changeAreaFamilyRoom As NXOpen.UIStyler.RealItem
    Private changeAspectFamilyRoom As NXOpen.UIStyler.RealItem
    Private changeSep14 As NXOpen.UIStyler.Separator
    Private changeLabel11P27 As NXOpen.UIStyler.LabelItem
    Private changeAreaMasterBedroom As NXOpen.UIStyler.RealItem
    Private changeAspectMasterBedroom As NXOpen.UIStyler.RealItem
    Private changeSep14P30 As NXOpen.UIStyler.Separator
    Private changeLabel11P31 As NXOpen.UIStyler.LabelItem
    Private changeAreaMasterBathroom As NXOpen.UIStyler.RealItem
    Private changeAspectMasterBathroom As NXOpen.UIStyler.RealItem
    Private changeSep14P34 As NXOpen.UIStyler.Separator
    Private changeLabel11P35 As NXOpen.UIStyler.LabelItem
    Private changeAreaLivingRoom As NXOpen.UIStyler.RealItem
    Private changeAspectLivingRoom As NXOpen.UIStyler.RealItem
    Private changeSep14P38 As NXOpen.UIStyler.Separator
    Private changeLabel11P39 As NXOpen.UIStyler.LabelItem
    Private changeAreaPatio As NXOpen.UIStyler.RealItem
    Private changeAspectPatio As NXOpen.UIStyler.RealItem
    Private changeSep14P42 As NXOpen.UIStyler.Separator
    Private changeLabel11P43 As NXOpen.UIStyler.LabelItem
    Private changeAreaGuestBathroom As NXOpen.UIStyler.RealItem
    Private changeAspectGuestBathroom As NXOpen.UIStyler.RealItem
    Private changeSep14P46 As NXOpen.UIStyler.Separator
    Private changeLabel11P47 As NXOpen.UIStyler.LabelItem
    Private changeAreaGuestBedroom As NXOpen.UIStyler.RealItem
    Private changeAspectGuestBedroom As NXOpen.UIStyler.RealItem
    Private changeSep14P50 As NXOpen.UIStyler.Separator
    Private changeLabel11P51 As NXOpen.UIStyler.LabelItem
    Private changeAreaKidsBathroom As NXOpen.UIStyler.RealItem
    Private changeAspectKidsBathroom As NXOpen.UIStyler.RealItem
    Private changeSep14P54 As NXOpen.UIStyler.Separator
    Private changeLabel11P55 As NXOpen.UIStyler.LabelItem
    Private changeAreaKidsBedroom As NXOpen.UIStyler.RealItem
    Private changeAspectKidsBedroom As NXOpen.UIStyler.RealItem
    Private changeUiCreateRooms As NXOpen.UIStyler.PushButton
    Private changeUiCreateRoof As NXOpen.UIStyler.PushButton
    Private changeEvaluateCurrentHouse As NXOpen.UIStyler.PushButton
    Private changeSep49 As NXOpen.UIStyler.Separator
    Private changeCgBeg49 As NXOpen.UIStyler.CollapsibleGroup
    Private changeLabel50 As NXOpen.UIStyler.LabelItem
    Private changeGaProgramGeometryFile As NXOpen.UIStyler.PushButton
    Private changeOpenExcelFileGeometry As NXOpen.UIStyler.PushButton
    Private changeGaProgramGeometryFileMessage As NXOpen.UIStyler.LabelItem
    Private changeSep58 As NXOpen.UIStyler.Separator
    Private changeLabel50P0 As NXOpen.UIStyler.LabelItem
    Private changeGaProgramMaterialFile As NXOpen.UIStyler.PushButton
    Private changeOpenExcelFileMaterial As NXOpen.UIStyler.PushButton
    Private changeGaProgramMaterialFileMessage As NXOpen.UIStyler.LabelItem
    Private changeSep59 As NXOpen.UIStyler.Separator
    Private changeMutationOption As NXOpen.UIStyler.RadioBox
    Private changeSep69 As NXOpen.UIStyler.Separator
    Private changeNumGenerationsAlltogether As NXOpen.UIStyler.IntegerItem
    Private changeNumGenerationsOrientation As NXOpen.UIStyler.IntegerItem
    Private changeNumGenerationsWindows As NXOpen.UIStyler.IntegerItem
    Private changeNumGenerationsAspect As NXOpen.UIStyler.IntegerItem
    Private changeSep74 As NXOpen.UIStyler.Separator
    Private changeNumChildrenPerGenerations As NXOpen.UIStyler.IntegerItem
    Private changeRunGaGeometry As NXOpen.UIStyler.PushButton
    Private changeRunGaMaterial As NXOpen.UIStyler.PushButton
    Public Shared isDisposeCalled As Boolean
    

#Region " UI Styler Dialog Designer generator code " 
'------------------------------------------------------------------------------
' Constructor for NX Styler class
'------------------------------------------------------------------------------
    Public Sub New()
        Try
            theSession = Session.GetSession()
            theUI = UI.GetUI()
            theDialog = theUI.Styler.CreateStylerDialog("BEM_House.dlg")
            InitializeUIStylerDialog()
            isDisposeCalled = False
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Sub

'------------------------------------------------------------------------------
' This method is required for UI styler dialog creation
'------------------------------------------------------------------------------
    Private Sub InitializeUIStylerDialog()
    '------------------------------------------------------------------------------
    ' The following code snippets initializes all the styler items and associate
    ' respective callbacks. Attributes of the styler item can be accessed and
    ' modified only after calling Show() or RegisterWithUiMenu().
    '------------------------------------------------------------------------------
        Try
            changeDialog = theDialog.GetStylerItem("UF_STYLER_DIALOG_INDEX", NXOpen.UIStyler.Dialog.ItemType.DialogItem)
            changeDialog.AddConstructHandler(AddressOf refresh, False)
            changeDialog.AddOkayHandler(AddressOf ok_cb, False)
            changeDialog.AddApplyHandler(AddressOf apply_cb, False)
            changeCgBeg1 = theDialog.GetStylerItem("CG_BEG_1", NXOpen.UIStyler.Dialog.ItemType.CollapsibleGroup)
            changeCity = theDialog.GetStylerItem("CITY", NXOpen.UIStyler.Dialog.ItemType.OptionMenu)
            changeCity.AddActivateHandler(AddressOf refresh, False)
            changeXAngle = theDialog.GetStylerItem("X_ANGLE", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeXAngle.AddActivateHandler(AddressOf refresh, False)
            changeLabel3 = theDialog.GetStylerItem("LABEL_3", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeSolstice = theDialog.GetStylerItem("SOLSTICE", NXOpen.UIStyler.Dialog.ItemType.OptionMenu)
            changeSolstice.AddActivateHandler(AddressOf refresh, False)
            changeCgBeg0 = theDialog.GetStylerItem("CG_BEG_0", NXOpen.UIStyler.Dialog.ItemType.CollapsibleGroup)
            changeHeight = theDialog.GetStylerItem("HEIGHT", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeHeight.AddActivateHandler(AddressOf refresh, False)
            changeRoofHeight = theDialog.GetStylerItem("ROOF_HEIGHT", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeRoofHeight.AddActivateHandler(AddressOf refresh, False)
            changeWindowAreaDefault = theDialog.GetStylerItem("WINDOW_AREA_DEFAULT", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeWindowAreaDefault.AddActivateHandler(AddressOf refresh, False)
            changeWindowAspectDefault = theDialog.GetStylerItem("WINDOW_ASPECT_DEFAULT", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeWindowAspectDefault.AddActivateHandler(AddressOf refresh, False)
            changeTI = theDialog.GetStylerItem("T_I", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeTI.AddActivateHandler(AddressOf refresh, False)
            changeSep12 = theDialog.GetStylerItem("SEP_12", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeInputChromosomeString = theDialog.GetStylerItem("INPUT_CHROMOSOME_STRING", NXOpen.UIStyler.Dialog.ItemType.StringItem)
            changeInputChromosomeString.AddActivateHandler(AddressOf refresh, False)
            changeBuildHouseFromChromosome = theDialog.GetStylerItem("BUILD_HOUSE_FROM_CHROMOSOME", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeBuildHouseFromChromosome.AddActivateHandler(AddressOf refresh, False)
            changeCgBeg8 = theDialog.GetStylerItem("CG_BEG_8", NXOpen.UIStyler.Dialog.ItemType.CollapsibleGroup)
            changeLabel9 = theDialog.GetStylerItem("LABEL_9", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeLabel10 = theDialog.GetStylerItem("LABEL_10", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeLabel11 = theDialog.GetStylerItem("LABEL_11", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaFamilyRoom = theDialog.GetStylerItem("AREA_FAMILY_ROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAreaFamilyRoom.AddActivateHandler(AddressOf refresh, False)
            changeAspectFamilyRoom = theDialog.GetStylerItem("ASPECT_FAMILY_ROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectFamilyRoom.AddActivateHandler(AddressOf refresh, False)
            changeSep14 = theDialog.GetStylerItem("SEP_14", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P27 = theDialog.GetStylerItem("LABEL_11_P_27", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaMasterBedroom = theDialog.GetStylerItem("AREA_MASTER_BEDROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectMasterBedroom = theDialog.GetStylerItem("ASPECT_MASTER_BEDROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P30 = theDialog.GetStylerItem("SEP_14_P_30", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P31 = theDialog.GetStylerItem("LABEL_11_P_31", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaMasterBathroom = theDialog.GetStylerItem("AREA_MASTER_BATHROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectMasterBathroom = theDialog.GetStylerItem("ASPECT_MASTER_BATHROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P34 = theDialog.GetStylerItem("SEP_14_P_34", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P35 = theDialog.GetStylerItem("LABEL_11_P_35", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaLivingRoom = theDialog.GetStylerItem("AREA_LIVING_ROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectLivingRoom = theDialog.GetStylerItem("ASPECT_LIVING_ROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P38 = theDialog.GetStylerItem("SEP_14_P_38", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P39 = theDialog.GetStylerItem("LABEL_11_P_39", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaPatio = theDialog.GetStylerItem("AREA_PATIO", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectPatio = theDialog.GetStylerItem("ASPECT_PATIO", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P42 = theDialog.GetStylerItem("SEP_14_P_42", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P43 = theDialog.GetStylerItem("LABEL_11_P_43", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaGuestBathroom = theDialog.GetStylerItem("AREA_GUEST_BATHROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectGuestBathroom = theDialog.GetStylerItem("ASPECT_GUEST_BATHROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P46 = theDialog.GetStylerItem("SEP_14_P_46", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P47 = theDialog.GetStylerItem("LABEL_11_P_47", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaGuestBedroom = theDialog.GetStylerItem("AREA_GUEST_BEDROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectGuestBedroom = theDialog.GetStylerItem("ASPECT_GUEST_BEDROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P50 = theDialog.GetStylerItem("SEP_14_P_50", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P51 = theDialog.GetStylerItem("LABEL_11_P_51", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaKidsBathroom = theDialog.GetStylerItem("AREA_KIDS_BATHROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectKidsBathroom = theDialog.GetStylerItem("ASPECT_KIDS_BATHROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeSep14P54 = theDialog.GetStylerItem("SEP_14_P_54", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel11P55 = theDialog.GetStylerItem("LABEL_11_P_55", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeAreaKidsBedroom = theDialog.GetStylerItem("AREA_KIDS_BEDROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeAspectKidsBedroom = theDialog.GetStylerItem("ASPECT_KIDS_BEDROOM", NXOpen.UIStyler.Dialog.ItemType.RealItem)
            changeUiCreateRooms = theDialog.GetStylerItem("UI_CREATE_ROOMS", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeUiCreateRooms.AddActivateHandler(AddressOf refresh, False)
            changeUiCreateRoof = theDialog.GetStylerItem("UI_CREATE_ROOF", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeUiCreateRoof.AddActivateHandler(AddressOf refresh, False)
            changeEvaluateCurrentHouse = theDialog.GetStylerItem("EVALUATE_CURRENT_HOUSE", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeEvaluateCurrentHouse.AddActivateHandler(AddressOf refresh, False)
            changeSep49 = theDialog.GetStylerItem("SEP_49", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeCgBeg49 = theDialog.GetStylerItem("CG_BEG_49", NXOpen.UIStyler.Dialog.ItemType.CollapsibleGroup)
            changeLabel50 = theDialog.GetStylerItem("LABEL_50", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeGaProgramGeometryFile = theDialog.GetStylerItem("GA_PROGRAM_GEOMETRY_FILE", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeGaProgramGeometryFile.AddActivateHandler(AddressOf refresh, False)
            changeOpenExcelFileGeometry = theDialog.GetStylerItem("OPEN_EXCEL_FILE_GEOMETRY", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeOpenExcelFileGeometry.AddActivateHandler(AddressOf refresh, False)
            changeGaProgramGeometryFileMessage = theDialog.GetStylerItem("GA_PROGRAM_GEOMETRY_FILE_MESSAGE", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeSep58 = theDialog.GetStylerItem("SEP_58", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeLabel50P0 = theDialog.GetStylerItem("LABEL_50_P_0", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeGaProgramMaterialFile = theDialog.GetStylerItem("GA_PROGRAM_MATERIAL_FILE", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeGaProgramMaterialFile.AddActivateHandler(AddressOf ga_program_geometry_file_p_1_act_cb, False)
            changeOpenExcelFileMaterial = theDialog.GetStylerItem("OPEN_EXCEL_FILE_MATERIAL", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeOpenExcelFileMaterial.AddActivateHandler(AddressOf open_excel_file_geometry_p_2_act_cb, False)
            changeGaProgramMaterialFileMessage = theDialog.GetStylerItem("GA_PROGRAM_MATERIAL_FILE_MESSAGE", NXOpen.UIStyler.Dialog.ItemType.LabelItem)
            changeSep59 = theDialog.GetStylerItem("SEP_59", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeMutationOption = theDialog.GetStylerItem("MUTATION_OPTION", NXOpen.UIStyler.Dialog.ItemType.RadioBox)
            changeMutationOption.AddValueChangedHandler(AddressOf refresh, False)
            changeSep69 = theDialog.GetStylerItem("SEP_69", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeNumGenerationsAlltogether = theDialog.GetStylerItem("NUM_GENERATIONS_ALLTOGETHER", NXOpen.UIStyler.Dialog.ItemType.IntegerItem)
            changeNumGenerationsAlltogether.AddActivateHandler(AddressOf refresh, False)
            changeNumGenerationsOrientation = theDialog.GetStylerItem("NUM_GENERATIONS_ORIENTATION", NXOpen.UIStyler.Dialog.ItemType.IntegerItem)
            changeNumGenerationsOrientation.AddActivateHandler(AddressOf refresh, False)
            changeNumGenerationsWindows = theDialog.GetStylerItem("NUM_GENERATIONS_WINDOWS", NXOpen.UIStyler.Dialog.ItemType.IntegerItem)
            changeNumGenerationsWindows.AddActivateHandler(AddressOf refresh, False)
            changeNumGenerationsAspect = theDialog.GetStylerItem("NUM_GENERATIONS_ASPECT", NXOpen.UIStyler.Dialog.ItemType.IntegerItem)
            changeNumGenerationsAspect.AddActivateHandler(AddressOf refresh, False)
            changeSep74 = theDialog.GetStylerItem("SEP_74", NXOpen.UIStyler.Dialog.ItemType.Separator)
            changeNumChildrenPerGenerations = theDialog.GetStylerItem("NUM_CHILDREN_PER_GENERATIONS", NXOpen.UIStyler.Dialog.ItemType.IntegerItem)
            changeNumChildrenPerGenerations.AddActivateHandler(AddressOf refresh, False)
            changeRunGaGeometry = theDialog.GetStylerItem("RUN_GA_GEOMETRY", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeRunGaGeometry.AddActivateHandler(AddressOf refresh, False)
            changeRunGaMaterial = theDialog.GetStylerItem("RUN_GA_MATERIAL", NXOpen.UIStyler.Dialog.ItemType.PushButton)
            changeRunGaMaterial.AddActivateHandler(AddressOf run_ga_geometry_p_4_act_cb, False)
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Sub

#End Region

' -------------------------- MENUBAR HOOKUP HELP Example ----------------------
' To launch this dialog from a NX menubar, you must follow the steps below:


'      1)Add the following lines to your MenuScript file in order to
'        associate a menu bar button with your dialog.  In this
'        example, a cascade menu will be created and will be
'        located just before the Help button on the main menubar.
'        The button, BEM_HOUSE_BTN is set up to launch your dialog and
'        will be positioned as the first button on your pulldown menu.
'        If you wish to add the button to an existing cascade, simply
'        add the 3 lines between MENU LAUNCH_CASCADE and END_OF_MENU
'        to your menuscript file.

'        The MenuScript file requires an extension of ".men".
'        Make sure that you add the extension to the file and place
'        the file in your startup directory:
'             $UGII_USER_DIR/startup or
'             $UGII_SITE_DIR/startup or
'             $UGII_VENDOR_DIR/startup directory

'        Move the contents between the dashed lines to your Menuscript file.
'        !-----------------------------------------------------------------------------
'        VERSION 120
' 
'        EDIT UG_GATEWAY_MAIN_MENUBAR
' 
'        BEFORE UG_HELP
'        CASCADE_BUTTON UISTYLER_DLG_CASCADE_BTN
'        LABEL Dialog Launcher
'        END_OF_BEFORE
' 
'        MENU UISTYLER_DLG_CASCADE_BTN
'        BUTTON BEM_HOUSE_BTN
'        LABEL Display BEMHouse dialog
'        ACTIONS BEM_House.dlg
'        END_OF_MENU
'        !-----------------------------------------------------------------------------

'      2)Issue a call to the function, RegisterWithUiMenu() from the Startup()
'        as shown below.
'        To use this call, remove the conditional definitions:
'             #If MENUBAR_COMMENTED_OUT Then
'             #End If

'      3)Place your compiled and linked DLL in 
'             $UGII_USER_DIR/startup or
'             $UGII_SITE_DIR/startup or
'             $UGII_VENDOR_DIR/startup directory.

'       NOTE:  The shared libraries must contain the proper extension .dll
'       to make ensure that it is recognized by the MenuScript.  If it does not
'       have the proper extension, it will NOT be recognized by MenuScript.

'       The action name you have provided in your MenuScript must correspond to
'       to the dialog name provided in the action structure.  This MUST match inorder
'       to bind your dlg file to your MenuScript button.

'      4)Copy your UIStyler dialog file to the proper directory.
'        All dialog files (.dlg) must be located in 
'             $UGII_USER_DIR/application or
'             $UGII_SITE_DIR/application or
'             $UGII_VENDOR_DIR/application directory
'------------------------------------------------------------------------------
#If MENUBAR_COMMENTED_OUT Then

    Public Shared Function Startup() As Integer
        Try
            theBEMHouse = New BEMHouse()
            ' The following method registers the dialog with a menu item
            theBEMHouse.RegisterWithUiMenu()

            Startup = 0

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Function ' Startup ends

    '------------------------------------------------------------------------------
    ' The flag "isTopDialog", informs menubar about the dialog location.
    ' This flag MUST match the resource set in the dialog.
    ' DO NOT ASSUME that changing this field will update the location of the dialog.
    ' Please use the UIStyler to indicate the position of the dialog.
    '------------------------------------------------------------------------------
    Public Sub RegisterWithUiMenu()
        Try
            Dim isTopDialog As boolean = False
            theDialog.RegisterWithUiMenu(isTopDialog)
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Sub
#End If ' MENUBAR_COMMENTED_OUT


' --------------- DIALOG CREATION FROM A CALLBACK HELP Example -----------------
' If you wish to have this dialog displayed from the callback of another
' UIStyler dialog, you should:


'      1)Make sure that the callback of your UIStyler dialog is
'        designated as a dialog building callback.
'      2)Remove the conditional definitions:
'             #If DISPLAY_FROM_CALLBACK Then
'             #End If

'      3)Your callback should issue a call to this method.


' All dialog files must be located in
'             $UGII_USER_DIR/application or
'             $UGII_SITE_DIR/application or
'             $UGII_VENDOR_DIR/application directory
'------------------------------------------------------------------------------
#If DISPLAY_FROM_CALLBACK Then

    Public Shared Sub <enter the name of your function>(ByRef response As NXOpen.UIStyler.DialogResponse)
        Try
            theBEMHouse = New BEMHouse()
            ' The following method shows the dialog immediately
            response = theBEMHouse.Show()
            BEMHouse.theBEMHouse.Dispose()
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Sub

#End If ' DISPLAY_FROM_CALLBACK


'---------------- DIALOG CREATION FROM A USER EXIT HELP Example ---------------
' An example is shown below to create this dialog from a user exit.
' All dialog files must be located in
'             $UGII_USER_DIR/application or
'             $UGII_SITE_DIR/application or
'             $UGII_VENDOR_DIR/application directory


'      1)Remove the conditional definitions:
'             #If DISPLAY_FROM_USER_EXIT Then
'             #End If

'      2)Add a user exit to the method name below, for example, Main().
'      3)Consider how your shared library will be unloaded.  Take a look
'        at the method GetUnloadOption().
'------------------------------------------------------------------------------
#If DISPLAY_FROM_USER_EXIT Then

    Public Shared Sub <enter a valid user exit here> ()
        Try
            Dim response As NXOpen.UIStyler.DialogResponse
            ' For Journal play back uncomment calls for LockAccess and UnlockAccess
            theBEMHouse = New BEMHouse()
            ' theUI.LockAccess()
            ' The following method shows the dialog immediately
            response = theBEMHouse.Show()
            theBEMHouse.Dispose()
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        Finally
            ' theUI.UnlockAccess()
        End Try
    End Sub ' User exit ends

    '------------------------------------------------------------------------------
    ' This method specifies how a shared image is unloaded from memory
    ' within NX. This method gives you the capability to unload an
    ' internal NX Open application or user  exit from NX. Specify any
    ' one of the three constants as a return value to determine the type
    ' of unload to perform:
    

    '    Immediately : unload the library as soon as the automation program has completed
    '    Explicitly  : unload the library from the "Unload Shared Image" dialog
    '    AtTermination : unload the library when the NX session terminates
    

    ' NOTE:  A program which associates NX Open applications with the menubar
    ' MUST NOT use this option since it will UNLOAD your NX Open application image
    ' from the menubar.
    '------------------------------------------------------------------------------
    Public Shared Function GetUnloadOption(ByVal arg As String) As Integer
        ' Return code to indicate this library can be unloaded
        ' by the user.
        Return CType(Session.LibraryUnloadOption.Explicitly, Integer)
        ' Return CType(Session.LibraryUnloadOption.Immediately, Integer)
        ' Return CType(Session.LibraryUnloadOption.AtTermination, Integer)
    End Function

    '------------------------------------------------------------------------------
    ' Following method cleanup any housekeeping chores that may be needed.
    ' This method is automatically called by NX.
    '------------------------------------------------------------------------------
    Public Shared Function UnloadLibrary(ByVal arg As String) As Integer
        Try
             If Not theBEMHouse Is Nothing Then theBEMHouse.Dispose()
            Return 0
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Function

#End If ' DISPLAY_FROM_USER_EXIT


    '------------------------------------------------------------------------------
    ' This method shows the dialog on the screen
    '------------------------------------------------------------------------------
    Public Function Show() As NXOpen.UIStyler.DialogResponse
        Try
            Show = theDialog.Show()
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Function


    '------------------------------------------------------------------------------
    ' Following method disposes all the class members
    '------------------------------------------------------------------------------
    Sub Dispose()
        Try
            If (isDisposeCalled = False) Then
                changeDialog.Dispose()
                changeCgBeg1.Dispose()
                changeCity.Dispose()
                changeXAngle.Dispose()
                changeLabel3.Dispose()
                changeSolstice.Dispose()
                changeCgBeg0.Dispose()
                changeHeight.Dispose()
                changeRoofHeight.Dispose()
                changeWindowAreaDefault.Dispose()
                changeWindowAspectDefault.Dispose()
                changeTI.Dispose()
                changeSep12.Dispose()
                changeInputChromosomeString.Dispose()
                changeBuildHouseFromChromosome.Dispose()
                changeCgBeg8.Dispose()
                changeLabel9.Dispose()
                changeLabel10.Dispose()
                changeLabel11.Dispose()
                changeAreaFamilyRoom.Dispose()
                changeAspectFamilyRoom.Dispose()
                changeSep14.Dispose()
                changeLabel11P27.Dispose()
                changeAreaMasterBedroom.Dispose()
                changeAspectMasterBedroom.Dispose()
                changeSep14P30.Dispose()
                changeLabel11P31.Dispose()
                changeAreaMasterBathroom.Dispose()
                changeAspectMasterBathroom.Dispose()
                changeSep14P34.Dispose()
                changeLabel11P35.Dispose()
                changeAreaLivingRoom.Dispose()
                changeAspectLivingRoom.Dispose()
                changeSep14P38.Dispose()
                changeLabel11P39.Dispose()
                changeAreaPatio.Dispose()
                changeAspectPatio.Dispose()
                changeSep14P42.Dispose()
                changeLabel11P43.Dispose()
                changeAreaGuestBathroom.Dispose()
                changeAspectGuestBathroom.Dispose()
                changeSep14P46.Dispose()
                changeLabel11P47.Dispose()
                changeAreaGuestBedroom.Dispose()
                changeAspectGuestBedroom.Dispose()
                changeSep14P50.Dispose()
                changeLabel11P51.Dispose()
                changeAreaKidsBathroom.Dispose()
                changeAspectKidsBathroom.Dispose()
                changeSep14P54.Dispose()
                changeLabel11P55.Dispose()
                changeAreaKidsBedroom.Dispose()
                changeAspectKidsBedroom.Dispose()
                changeUiCreateRooms.Dispose()
                changeUiCreateRoof.Dispose()
                changeEvaluateCurrentHouse.Dispose()
                changeSep49.Dispose()
                changeCgBeg49.Dispose()
                changeLabel50.Dispose()
                changeGaProgramGeometryFile.Dispose()
                changeOpenExcelFileGeometry.Dispose()
                changeGaProgramGeometryFileMessage.Dispose()
                changeSep58.Dispose()
                changeLabel50P0.Dispose()
                changeGaProgramMaterialFile.Dispose()
                changeOpenExcelFileMaterial.Dispose()
                changeGaProgramMaterialFileMessage.Dispose()
                changeSep59.Dispose()
                changeMutationOption.Dispose()
                changeSep69.Dispose()
                changeNumGenerationsAlltogether.Dispose()
                changeNumGenerationsOrientation.Dispose()
                changeNumGenerationsWindows.Dispose()
                changeNumGenerationsAspect.Dispose()
                changeSep74.Dispose()
                changeNumChildrenPerGenerations.Dispose()
                changeRunGaGeometry.Dispose()
                changeRunGaMaterial.Dispose()
                theDialog.Dispose()
            End If
            isDisposeCalled = True
        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
    End Sub

    '------------------------------------------------------------------------------
    '------------------------- UIStyler Callback Functions ------------------------
    '------------------------------------------------------------------------------


    '------------------------------------------------------------------------------
    ' Callback Name: refresh
    ' Following callback is associated with the "changeDialog" Styler item.
    ' Input: eventObject - object of UIStyler.StylerEvent class
    '------------------------------------------------------------------------------
    Public Function refresh(ByVal eventObject As NXOpen.UIStyler.StylerEvent) As NXOpen.UIStyler.DialogState
        Try
            

            ' ---- Enter your callback code here -----
            

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
        ' Callback acknowledged, do not terminate dialog
        refresh = NXOpen.UIStyler.DialogState.ContinueDialog
        ' A return value of NXOpen.UIStyler.DialogState.ExitDialog will not be accepted
        ' for this callback type. You must continue dialog construction.
    End Function

    '------------------------------------------------------------------------------
    ' Callback Name: ok_cb
    ' Following callback is associated with the "changeDialog" Styler item.
    ' Input: eventObject - object of UIStyler.StylerEvent class
    '------------------------------------------------------------------------------
    Public Function ok_cb(ByVal eventObject As NXOpen.UIStyler.StylerEvent) As NXOpen.UIStyler.DialogState
        Try
            

            ' ---- Enter your callback code here -----
            

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
        ' Callback acknowledged, terminate dialog
        ' It is STRONGLY recommanded that you exit your
        ' callback with NXOpen.UIStyler.DialogState.ExitDialog in a ok callback.
        ok_cb = NXOpen.UIStyler.DialogState.ExitDialog
    End Function

    '------------------------------------------------------------------------------
    ' Callback Name: apply_cb
    ' Following callback is associated with the "changeDialog" Styler item.
    ' Input: eventObject - object of UIStyler.StylerEvent class
    '------------------------------------------------------------------------------
    Public Function apply_cb(ByVal eventObject As NXOpen.UIStyler.StylerEvent) As NXOpen.UIStyler.DialogState
        Try
            

            ' ---- Enter your callback code here -----
            

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
        ' Callback acknowledged, do not terminate dialog
        ' A return value of NXOpen.UIStyler.DialogState.ExitDialog will not be accepted
        ' for this callback type. You must respond to your apply button.
        apply_cb = NXOpen.UIStyler.DialogState.ContinueDialog
    End Function

    '------------------------------------------------------------------------------
    ' Callback Name: ga_program_geometry_file_p_1_act_cb
    ' Following callback is associated with the "changeGaProgramMaterialFile" Styler item.
    ' Input: eventObject - object of UIStyler.StylerEvent class
    '------------------------------------------------------------------------------
    Public Function ga_program_geometry_file_p_1_act_cb(ByVal eventObject As NXOpen.UIStyler.StylerEvent) As NXOpen.UIStyler.DialogState
        Try
            

            ' ---- Enter your callback code here -----
            

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
        ' Callback acknowledged, do not terminate dialog
        ga_program_geometry_file_p_1_act_cb = NXOpen.UIStyler.DialogState.ContinueDialog
        ' or Callback acknowledged, terminate dialog.
        ' ga_program_geometry_file_p_1_act_cb = NXOpen.UIStyler.DialogState.ExitDialog
    End Function

    '------------------------------------------------------------------------------
    ' Callback Name: open_excel_file_geometry_p_2_act_cb
    ' Following callback is associated with the "changeOpenExcelFileMaterial" Styler item.
    ' Input: eventObject - object of UIStyler.StylerEvent class
    '------------------------------------------------------------------------------
    Public Function open_excel_file_geometry_p_2_act_cb(ByVal eventObject As NXOpen.UIStyler.StylerEvent) As NXOpen.UIStyler.DialogState
        Try
            

            ' ---- Enter your callback code here -----
            

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
        ' Callback acknowledged, do not terminate dialog
        open_excel_file_geometry_p_2_act_cb = NXOpen.UIStyler.DialogState.ContinueDialog
        ' or Callback acknowledged, terminate dialog.
        ' open_excel_file_geometry_p_2_act_cb = NXOpen.UIStyler.DialogState.ExitDialog
    End Function

    '------------------------------------------------------------------------------
    ' Callback Name: run_ga_geometry_p_4_act_cb
    ' Following callback is associated with the "changeRunGaMaterial" Styler item.
    ' Input: eventObject - object of UIStyler.StylerEvent class
    '------------------------------------------------------------------------------
    Public Function run_ga_geometry_p_4_act_cb(ByVal eventObject As NXOpen.UIStyler.StylerEvent) As NXOpen.UIStyler.DialogState
        Try
            

            ' ---- Enter your callback code here -----
            

        Catch ex As NXException
            ' ---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("UI Styler", NXMessageBox.DialogType.Error, ex.Message)
        End Try
        ' Callback acknowledged, do not terminate dialog
        run_ga_geometry_p_4_act_cb = NXOpen.UIStyler.DialogState.ContinueDialog
        ' or Callback acknowledged, terminate dialog.
        ' run_ga_geometry_p_4_act_cb = NXOpen.UIStyler.DialogState.ExitDialog
    End Function

End Class
